import "./globals.css";
import { Work_Sans } from "@next/font/google";
import { ReduxProvider } from "../redux/provider";
import { ThemeRegistry } from "@/theme/themeRegistry";

// instantiate the Work_Sans object by providing the subsets.
const workSans = Work_Sans({
  subsets: ["latin"],
  // weight: ["400", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head></head> */}
      {/* <ThemeRegistry> */}
      <body className={workSans.className}>
        {/* import the custom provider component */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
      {/* </ThemeRegistry> */}
    </html>
  );
}
