import "./globals.css";
import { Work_Sans } from "next/font/google";
import { ReduxProvider } from "../redux/provider";
import ThemeRegistry from "./ThemeRegistry";
import { Footer, NavBar } from ".";
import { CssBaseline } from "@mui/material";

// instantiate the Work_Sans object by providing the subsets.
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});
export const metadata = {
  title: "TradeTracker Trading Journal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const { children } = props;
  return (
    <html lang="en">
      <body className={workSans.className}>
        <ReduxProvider>
          <ThemeRegistry options={{ key: "mui" }}>
            <CssBaseline />
            <NavBar />
            {children}
            <Footer />
          </ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}

// suppressHydrationWarning props in html
